# Copyright 2022, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

# Build web server demo app on pull request

name: Web Server

on:
  pull_request:

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ODROID_XU4, ODROID_C2, TX2]
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.1'
        bundler-cache: true
    - run: pip3 install -U camkes-deps
    - run: sudo apt-get install doxygen
    - uses: seL4/ci-actions/webserver@master
      with:
        platform: ${{ matrix.platform }}
